name: polls_app

services:
  app:
    image: app:latest
    build:
      context: .
    volumes:
      - django_var:/app/var
      - django_static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
  
  app-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - django_static:/static:ro
    depends_on:
      - app
  
  migrate:
    image: app:latest
    build:
      context: .
    volumes:
      - django_var:/app/var
    command: ["python3", "manage.py", "migrate"]
  
  loaddata:
    image: app:latest
    build:
      context: .
    volumes:
      - django_var:/app/var
    command: ["python3", "manage.py", "loaddata", "db.json"]

volumes:
  django_var:
  django_static:

