# Generated by Django 6.0.6 on 2026-06-08 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0002_pollquestion_pollchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls_api.pollquestion'),
        ),
    ]
