# Generated by Django 6.0.6 on 2026-06-13 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_api', '0003_alter_pollchoice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='exp_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='votes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
